In [ ]:
# 객체지향 프로그래밍: 객체의 개념을 프로그래밍에 도입
# 객체: 변수, 함수도 구성 -> 메모리에 올라간 상태
# 클래스: 변수들과 함수들이 어떻게 구성되는지의 설계도 -> 변수들을 정의, 함수들을 정의
# -> 클래스만 정의 -> 사용 불가, 클래스를 이용해서 객체로 만들어야 사용 가능

# class 클래스이름:
#   변수들과 함수들을 정의
#   변수 = 클래스이름() => 객체 생성
# 객체 활용: 변수.객체이름, 변수.객체함수(), 메서드

# 클래스 생성성
class Cookie():
    pass

# 객체 생성
c1=Cookie()
# 새로운 객체 생성
c2=Cookie()

print(id(c1), type(c1))
print(id(c2), type(c2))


2390594436608 <class '__main__.Cookie'>
2390594134864 <class '__main__.Cookie'>


In [ ]:
# 사칙연산을 하는 클래스 정의: 클래스 이름, 변수, 함수
# 변수는 두개, 함수(메서드 4개)

class FourCal:

    # 초기화(변수 선언 -> 최초 데이터 할당) 메서드
    # 필요 변수 생성, 값 초기화
    def __init__(self,first, second):
        self.first = first
        self.second = second

    # 클래스에서 함수 정의시 반드시 self 매개변수 받아야한다
    # self = 객체 자신을 가르키는 변수 (객체의 주소)
    def setdata(self, first, second):
        self.first = first
        self.second = second

    # 사칙연산 함수
    def add(self):
        return self.first+self.second
    
    def sub(self):
        return self.first-self.second
    
    def mul(self):
        return self.first*self.second
    
    def div(self):
        return self.first/self.second





In [ ]:
cal_1 = FourCal()
type(cal_1)

cal_1.setdata(10,20)


print(cal_1.first, cal_1.second)


# 그냥 정하면 안된다
cal_2 = FourCal()
cal_2.first


cal_3 = FourCal()

In [19]:

cal_4 = FourCal(100, 200)
cal_4.first

100

In [20]:
cal_5=FourCal(10,7)

print(cal_5.first, cal_5.second)
print(cal_5.add())
print(cal_5.sub())
print(cal_5.mul())
print(cal_5.div())

10 7
17
3
70
1.4285714285714286


In [25]:
# 학생 class 생성 -> 객체 생성
# 학생변수: 학번, 이름, 국어점수, 영어점수, 수학점수
# 기능: 전체 데이터 출력 메서드 (이름, 학번, 총점, 평균)
#       총점 계산
#       평균 계산
# 시뮬레이션: 테스트 학생 데이터 생성 -> 결과 출력


class Student:

    # 초기화(변수 선언 -> 최초 데이터 할당) 메서드
    # 필요 변수 생성, 값 초기화
    def __init__(self, stNum, stName, k_score, e_score, m_score):
        self.stNum = stNum
        self.stName = stName
        self.k_score = k_score
        self.e_score = e_score
        self.m_score = m_score


    def scoreSum(self):
        sum = self.k_score+self.e_score+self.m_score
        return sum
    
    def scoreAvg(self):
        avg = self.scoreSum()/3
        return avg



    def printData(self):
        print('학생 번호: '+self.stNum)
        print('학생 이름: '+self.stName)
        print('학생 총점: '+str(self.scoreSum()))
        print('학생 평균: '+str(self.scoreAvg()))

st_1=Student('0001', 'Kim', 80,90,85)

st_1.printData()



학생 번호: 0001
학생 이름: Kim
학생 총점: 255
학생 평균: 85.0


In [27]:
# 리스트로 다중 입력력

students = [
    Student('0001', 'Kim', 80,90,85),
    Student('0002', 'Lee', 80,90,85),
    Student('0003', 'Choi', 80,90,85),
    Student('0004', 'Park', 80,90,85),
    Student('0005', 'Ha', 80,90,85),
]


for s in students:
    s.printData()

학생 번호: 0001
학생 이름: Kim
학생 총점: 255
학생 평균: 85.0
학생 번호: 0002
학생 이름: Lee
학생 총점: 255
학생 평균: 85.0
학생 번호: 0003
학생 이름: Choi
학생 총점: 255
학생 평균: 85.0
학생 번호: 0004
학생 이름: Park
학생 총점: 255
학생 평균: 85.0
학생 번호: 0005
학생 이름: Ha
학생 총점: 255
학생 평균: 85.0


In [ ]:
# 클래스의 상속: 새로운 클래스를 만들 때 기존의 클래스 멤버를 받아서 생성하는 방법
# class 이름 (부모 클래스)

class MoreFourCal(FourCal):
    def pow(self):
        return self.first**self.second
    
    def div(self):
        if self.second==0:
            return 0
        else:
            return self.first/self.second


# 상속으로 추가 함수 컨트롤
mcal_2=MoreFourCal(100,0)
print(mcal_2.add())
print(mcal_2.mul())
print(mcal_2.sub())
print(mcal_2.div())
print(mcal_2.pow())

100
0
100
0
1


### 표준 모듈

In [ ]:
# 표준 모듈: datetime

import datetime

day1 = datetime.date(2025, 6, 12)

print(day1)


# date 빼기 연산
day2 = datetime.date(2025, 1, 1)

print(day1-day2)

2025-06-12
162 days, 0:00:00


In [ ]:
# 표준 모듈: time

import time

# float 형태
time.time()

# 현재 컴퓨터가 가진 로컬 시간
time.localtime()

# 미국 시간?
time.ctime()



'Thu Jun 12 15:58:52 2025'

In [ ]:
# 표준 모듈: random

import random

# 0.000000 <= R < 1
random.random()

# 특정 값 사이의 랜덤 정수 값
# random.randint(60, 100) -> 60 에서 100사이 정수수


list_score =[]

for s in range(0,10):
    list_score.append(random.randint(60, 100))

print(list_score)




# 리스트 안에서 요소 하나를 랜덤으로 선택
print(random.choice([1,2,3,4,5,6,7,8]))


# 리스트 안에서 지정 갯수의 요소들을 랜덤으로 선택
print(random.sample([1,2,3,4,5,6,7,8,9], 3))




[65, 98, 85, 80, 63, 65, 100, 67, 65, 100]
2
[5, 4, 9]


In [52]:
# 표준 모듈: OS

import os

# 환경 정보
os.environ

# 디렉토리 이동
os.chdir('C:\\project\\py_project')

# 현재 위치 확인
print(os.getcwd())

# 디렉토리 생성
os.mkdir('a4_test')

# 디렉토리 삭제
os.rmdir('a4_test')

C:\project\py_project


In [ ]:
# 표준 모듈: json

import json


#  json 파일 열고 읽기
with open('a4_data.json', 'r', encoding='utf-8') as f:
          data = json.load(f)

print(data, type(data))


# 문자열로 변환
json_str_data = json.dumps(data)

print(json_str_data, type(json_str_data))

{'name': 'Son', 'age': 30, 'number': 7} <class 'dict'>
{"name": "Son", "age": 30, "number": 7} <class 'str'>


### 외부 모듈

In [ ]:
import numpy as np


# 배열 연산
arr=np.array([1,2,3,4,5])
print(arr, type(arr))
arr+10

[1 2 3 4 5] <class 'numpy.ndarray'>


array([11, 12, 13, 14, 15])

In [ ]:
# 배열의 생성
# 0으로 채워지는 배열 생성
zeros = np.zeros((1,3))
print(zeros)
print()

# 1로 채우는 배열
ones = np.ones((5,5))
print(ones)
print()


# 일련번호 생성 배열
# 0~10 사이의 숫자를 2 간격으로 생성
seq_1 = np.arange(0, 10, 2)
print(seq_1)
print()


# 지정 범위 안에서 동일 간격으로 숫자 생성
# 0~1 5개로 구분
linspace = np.linspace(1, 10, 5)
print(linspace)
print()


# 배열의 속성 확인
print('배열의 속성 확인')

arr1= np.array([[1,2,3], [4,5,6]])
print(type(arr1))
print(arr1.shape)   # 배열의 크기 (행, 열)
print(arr1.ndim)    # 배열의 차원
print(arr1.size)    # 요소의 갯수
print(arr1.dtype)   # 데이터 타입


[[0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[0 2 4 6 8]

[ 1.    3.25  5.5   7.75 10.  ]

<class 'numpy.ndarray'>
(2, 3)
2
6
int64
